name: bill_manager
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.69.0  # Update to the latest version
  collection: ^1.18.0  # Update to the latest version
  file_picker: ^8.1.2  # Update to the latest version
  flutter_lints: ^5.0.0  # Keep this line only once
  intl: ^0.19.0  # Update to the latest version
  leak_tracker: ^10.0.5  # Update to the latest version
  leak_tracker_flutter_testing: ^3.0.5  # Update to the latest version
  lints: ^5.1.0  # Update to the latest version
  material_color_utilities: ^0.11.1  # Update to the latest version
  meta: ^1.15.0  # Update to the latest version
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

# The "flutter_lints" package below contains a set of recommended lints to
# encourage good coding practices. The lint set provided by the package is
# activated in the `analysis_options.yaml` file located at the root of your
# package. See that file for information about deactivating specific lint
# rules and activating additional ones.
